site_name: "Iydon Docs"
site_description: "Iydon's common tools"
repo_url: "https://github.com/iydon/iydon"
edit_uri: "blob/main/docs/"
repo_name: "iydon/iydon"

theme:
    language: en
    name: material
    features:
        - navigation.tabs
        - navigation.top
    palette:
        primary: indigo

plugins:
    - autorefs
    - mkdocstrings
    - search

nav:
    - "Home": "index.md"
    - "API":
        - "iydon.glhf":
            - "end": "api/glhf/end.md"
            - "silver_bullet": "api/glhf/silver_bullet.md"
        - "iydon.rust":
            - "option": "api/rust/option.md"
            - "result": "api/rust/result.md"
